### ISSUE TITLE
Add support for cloud-init Networking Config Version 2

### ISSUE THREAD

**Issue by ader1990** [cloudbase/cloudbase-init#134]
Cloudbase-init already supports networking config format v1 (https://cloudinit.readthedocs.io/en/20.1/topics/network-config-format-v1.html) and the legacy ENI (https://cloudinit.readthedocs.io/en/20.1/topics/network-config-format-eni.html).

Cloudbase-init does not support yet the Networking Config Version 2 (https://cloudinit.readthedocs.io/en/20.1/topics/network-config-format-v2.html).

**Comment by FlorianLaunay** [comment]
Hi @ader1990
Could you please close this issue ? It was solved by f0fe66b in release [1.1.5](https://github.com/cloudbase/cloudbase-init/releases/tag/1.1.5).

**Comment by rgl** [comment]
not sure how it was solved, but in a ubuntu 24.04 machine, with this network-config:

```yaml
          version: 2
          ethernets:
            eth0:
              dhcp4: false
              dhcp6: false
              addresses:
                - "{{ ansible_host }}/24"
              gateway4: "{{ vm_gateway }}"
              nameservers:
                addresses:
                  - "{{ vm_gateway }}"
```

it works fine, and set the static IP address.

but, the same network-config with cloudbase-init 1.1.8, in a windows 2022 machine, it does not really work. cloudbase-init has this error in the log:

```
2026-05-06 00:58:25.778 4484 ERROR cloudbaseinit.init [-] plugin 'NetworkConfigPlugin' failed with error ''NoneType' object has no attribute 'lower''
2026-05-06 00:58:25.778 4484 ERROR cloudbaseinit.init [-] 'NoneType' object has no attribute 'lower': AttributeError: 'NoneType' object has no attribute 'lower'
2026-05-06 00:58:25.778 4484 ERROR cloudbaseinit.init Traceback (most recent call last):
2026-05-06 00:58:25.778 4484 ERROR cloudbaseinit.init   File "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\Lib\site-packages\cloudbaseinit\init.py", line 66, in _exec_plugin
2026-05-06 00:58:25.778 4484 ERROR cloudbaseinit.init     (status, reboot_required) = plugin.execute(service,
2026-05-06 00:58:25.778 4484 ERROR cloudbaseinit.init                                 ~~~~~~~~~~~~~~^^^^^^^^^
2026-05-06 00:58:25.778 4484 ERROR cloudbaseinit.init                                                shared_data)
2026-05-06 00:58:25.778 4484 ERROR cloudbaseinit.init                                                ^^^^^^^^^^^^
2026-05-06 00:58:25.778 4484 ERROR cloudbaseinit.init   File "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\Lib\site-packages\cloudbaseinit\plugins\common\networkconfig.py", line 307, in execute
2026-05-06 00:58:25.778 4484 ERROR cloudbaseinit.init     return self._process_network_details_v2(network_details)
2026-05-06 00:58:25.778 4484 ERROR cloudbaseinit.init            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
2026-05-06 00:58:25.778 4484 ERROR cloudbaseinit.init   File "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\Lib\site-packages\cloudbaseinit\plugins\common\networkconfig.py", line 295, in _process_network_details_v2
2026-05-06 00:58:25.778 4484 ERROR cloudbaseinit.init     NetworkConfigPlugin._process_physical_links(
2026-05-06 00:58:25.778 4484 ERROR cloudbaseinit.init     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
2026-05-06 00:58:25.778 4484 ERROR cloudbaseinit.init         osutils, network_details)
2026-05-06 00:58:25.778 4484 ERROR cloudbaseinit.init         ^^^^^^^^^^^^^^^^^^^^^^^^^
2026-05-06 00:58:25.778 4484 ERROR cloudbaseinit.init   File "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\Lib\site-packages\cloudbaseinit\plugins\common\networkconfig.py", line 197, in _process_physical_links
2026-05-06 00:58:25.778 4484 ERROR cloudbaseinit.init     adapter_name = osutils.get_network_adapter_name_by_mac_address(
2026-05-06 00:58:25.778 4484 ERROR cloudbaseinit.init         link.mac_address)
2026-05-06 00:58:25.778 4484 ERROR cloudbaseinit.init   File "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\Lib\site-packages\cloudbaseinit\osutils\windows.py", line 808, in get_network_adapter_name_by_mac_address
2026-05-06 00:58:25.778 4484 ERROR cloudbaseinit.init     net_addr["mac_address"].lower() == mac_address.lower()]
2026-05-06 00:58:25.778 4484 ERROR cloudbaseinit.init                                        ^^^^^^^^^^^^^^^^^
2026-05-06 00:58:25.778 4484 ERROR cloudbaseinit.init AttributeError: 'NoneType' object has no attribute 'lower'
2026-05-06 00:58:25.778 4484 ERROR cloudbaseinit.init 
```

it seems the current implementation is somewhat different than what cloud-init currently supports. for example, the `name` property is supposed to match a network interface by name (and even supports wildcards), but in cloudbase-init, it does not seem to do anything:

```yaml
          version: 2
          ethernets:
            eth0:
              name: Ethernet 2
              dhcp4: false
              dhcp6: false
              addresses:
                - "{{ ansible_host }}/24"
              gateway4: "{{ vm_gateway }}"
              nameservers:
                addresses:
                  - "{{ vm_gateway }}"
```

How do I configure a static IP address without using a mac address (its generated automatically; its not static)? For example, to a VM has this `ipconfig /all` output:


```console
$ PS C:\Users\vagrant> ipconfig /all

Windows IP Configuration

   Host Name . . . . . . . . . . . . : vm1
   Primary Dns Suffix  . . . . . . . :
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No
   DNS Suffix Search List. . . . . . : lan

Ethernet adapter Ethernet 2:

   Connection-specific DNS Suffix  . : lan
   Description . . . . . . . . . . . : Microsoft Hyper-V Network Adapter #2
   Physical Address. . . . . . . . . : 00-15-5D-08-16-2A
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   IPv4 Address. . . . . . . . . . . : 192.168.8.124(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Lease Obtained. . . . . . . . . . : Saturday, March 29, 1890 7:30:20 PM
   Lease Expires . . . . . . . . . . : Wednesday, May 6, 2026 12:58:38 PM
   Default Gateway . . . . . . . . . : 192.168.8.1
   DHCP Server . . . . . . . . . . . : 192.168.8.1
   DNS Servers . . . . . . . . . . . : 192.168.8.1
   NetBIOS over Tcpip. . . . . . . . : Enabled
```

its not clear how the network interface is matched by name either, the name of the adapter is "Ethernet 2" and the description is "Microsoft Hyper-V Network Adapter #2", so not sure how should that match.

but, trying with "Ethernet 2" instead of "eth0":

```yaml
          version: 2
          ethernets:
            Ethernet 2:
              dhcp4: false
              dhcp6: false
              addresses:
                - "{{ ansible_host }}/24"
              gateway4: "{{ vm_gateway }}"
              nameservers:
                addresses:
                  - "{{ vm_gateway }}"
```

does not work either. it throws an exception because the mac-address is not defined in the network-config. I do not want to define it either, because that's something that I do not known, it's generated at runtime.
