### ISSUE TITLE
BCDConfig plugin does not work

### ISSUE THREAD

**Issue by silentirk** [cloudbase/cloudbase-init#146]
Cloudbase-init version 1.1.4
Windows Server version: 2016, 2019, 2022 with the latest CUs

Unique disk ID is not changed and the next lines in the log appear:

2024-06-11 09:16:05.079 4000 INFO cloudbaseinit.init [-] Executing plugin 'BCDConfigPlugin'
2024-06-11 09:16:05.836 4000 ERROR cloudbaseinit.init [-] plugin 'BCDConfigPlugin' failed with error 'not enough values to unpack (expected 2, got 1)'
2024-06-11 09:16:05.867 4000 ERROR cloudbaseinit.init [-] not enough values to unpack (expected 2, got 1): ValueError: not enough values to unpack (expected 2, got 1)
2024-06-11 09:16:05.867 4000 ERROR cloudbaseinit.init Traceback (most recent call last):
2024-06-11 09:16:05.867 4000 ERROR cloudbaseinit.init   File "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\init.py", line 66, in _exec_plugin
2024-06-11 09:16:05.867 4000 ERROR cloudbaseinit.init     (status, reboot_required) = plugin.execute(service,
2024-06-11 09:16:05.867 4000 ERROR cloudbaseinit.init   File "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\plugins\windows\bootconfig.py", line 58, in execute
2024-06-11 09:16:05.867 4000 ERROR cloudbaseinit.init     bootconfig.enable_auto_recovery(CONF.bcd_enable_auto_recovery)
2024-06-11 09:16:05.867 4000 ERROR cloudbaseinit.init   File "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\utils\windows\bootconfig.py", line 91, in enable_auto_recovery
2024-06-11 09:16:05.867 4000 ERROR cloudbaseinit.init     current_store = _get_current_bcd_store()
2024-06-11 09:16:05.867 4000 ERROR cloudbaseinit.init   File "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\cloudbaseinit\utils\windows\bootconfig.py", line 59, in _get_current_bcd_store
2024-06-11 09:16:05.867 4000 ERROR cloudbaseinit.init     success, store = conn.BcdStore.OpenStore(File="")
2024-06-11 09:16:05.867 4000 ERROR cloudbaseinit.init ValueError: not enough values to unpack (expected 2, got 1)
2024-06-11 09:16:05.867 4000 ERROR cloudbaseinit.init

**Comment by ader1990** [comment]
Hello @Silentirk,

To better reproduce the environment and the issue, can you please give the values of the configs you used for the plugin? https://cloudbase-init.readthedocs.io/en/latest/plugins.html#bcd-config-main

Thank you.

**Comment by silentirk** [comment]
I don't add set_unique_boot_disk_id (bool: False, i think there's an error in the docs, as it seems to be True by default, if i read source code correctly) or bcd_enable_auto_recovery (bool: False) to my config.

**Comment by ader1990** [comment]
Thank you, @Silentirk. We could reproduce the issue locally, we will provide a fix as soon as possible.
The issue is related to the difference in how the `wmi` project and the newer `PyMI` project (that replaced WMI) handles WMI return values.
