### ISSUE TITLE
Unexpected COM Error in NetworkPlugin

### ISSUE THREAD

**Issue by panaceya** [cloudbase/cloudbase-init#50]
cloudbase-init.log:
```
2020-06-09 13:45:51.710 1456 INFO cloudbaseinit.init [-] Executing plugin 'NetworkConfigPlugin'
2020-06-09 13:45:51.710 1456 DEBUG cloudbaseinit.utils.classloader [-] Loading class 'cloudbaseinit.osutils.windows.WindowsUtils' load_class C:\Program Files\CloudBase\Python\lib\site-packages\cloudbaseinit\utils\classloader.py:27
2020-06-09 13:45:51.710 1456 INFO cloudbaseinit.plugins.common.networkconfig [-] Renaming network adapter "Ethernet 2" to "vEthernet"
2020-06-09 13:45:52.757 1456 DEBUG cloudbaseinit.plugins.common.networkconfig [-] Enable network adapter "vEthernet": True _process_link_common C:\Program Files\CloudBase\Python\lib\site-packages\cloudbaseinit\plugins\common\networkconfig.py:187
2020-06-09 13:45:53.210 1456 INFO cloudbaseinit.plugins.common.networkconfig [-] Setting static IP configuration on network adapter "vEthernet". IP: x.x.x.x, prefix length: 26, gateway: x.x.x.x, dns: ['1.1.1.1', '8.8.8.8']
2020-06-09 13:45:53.742 1456 DEBUG cloudbaseinit.osutils.windows [-] Removing existing IP address "169.254.191.95" from adapter "vEthernet" _set_static_network_config C:\Program Files\CloudBase\Python\lib\site-packages\cloudbaseinit\osutils\windows.py:980
2020-06-09 13:45:53.945 1456 DEBUG cloudbaseinit.osutils.windows [-] Removing existing route "255.255.255.255/32" from adapter "vEthernet" _set_static_network_config C:\Program Files\CloudBase\Python\lib\site-packages\cloudbaseinit\osutils\windows.py:989
2020-06-09 13:45:53.992 1456 DEBUG cloudbaseinit.osutils.windows [-] Removing existing route "224.0.0.0/4" from adapter "vEthernet" _set_static_network_config C:\Program Files\CloudBase\Python\lib\site-packages\cloudbaseinit\osutils\windows.py:989
2020-06-09 13:45:54.054 1456 ERROR cloudbaseinit.init [-] plugin 'NetworkConfigPlugin' failed with error '<x_wmi: Unexpected COM Error (-2147352567, 'Exception occurred.', (0, 'SWbemObjectEx', 'Invalid parameter ', None, 0, -2147217400), None)>': wmi.x_wmi: <x_wmi: Unexpected COM Error (-2147352567, 'Exception occurred.', (0, 'SWbemObjectEx', 'Invalid parameter ', None, 0, -2147217400), None)>
2020-06-09 13:45:54.101 1456 ERROR cloudbaseinit.init [-] <x_wmi: Unexpected COM Error (-2147352567, 'Exception occurred.', (0, 'SWbemObjectEx', 'Invalid parameter ', None, 0, -2147217400), None)>: wmi.x_wmi: <x_wmi: Unexpected COM Error (-2147352567, 'Exception occurred.', (0, 'SWbemObjectEx', 'Invalid parameter ', None, 0, -2147217400), None)>
2020-06-09 13:45:54.101 1456 ERROR cloudbaseinit.init Traceback (most recent call last):
2020-06-09 13:45:54.101 1456 ERROR cloudbaseinit.init   File "C:\Program Files\CloudBase\Python\lib\site-packages\wmi.py", line 603, in __getattr__
2020-06-09 13:45:54.101 1456 ERROR cloudbaseinit.init     return getattr(self.ole_object, attribute)
2020-06-09 13:45:54.101 1456 ERROR cloudbaseinit.init   File "C:\Program Files\CloudBase\Python\lib\site-packages\win32com\client\dynamic.py", line 516, in __getattr__
2020-06-09 13:45:54.101 1456 ERROR cloudbaseinit.init     ret = self._oleobj_.Invoke(retEntry.dispid,0,invoke_type,1)
2020-06-09 13:45:54.101 1456 ERROR cloudbaseinit.init pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'SWbemObjectEx', 'Invalid parameter ', None, 0, -2147217400), None)
2020-06-09 13:45:54.101 1456 ERROR cloudbaseinit.init 
2020-06-09 13:45:54.101 1456 ERROR cloudbaseinit.init During handling of the above exception, another exception occurred:
2020-06-09 13:45:54.101 1456 ERROR cloudbaseinit.init 
2020-06-09 13:45:54.101 1456 ERROR cloudbaseinit.init Traceback (most recent call last):
2020-06-09 13:45:54.101 1456 ERROR cloudbaseinit.init   File "C:\Program Files\CloudBase\Python\lib\site-packages\cloudbaseinit\init.py", line 67, in _exec_plugin
2020-06-09 13:45:54.101 1456 ERROR cloudbaseinit.init     shared_data)
2020-06-09 13:45:54.101 1456 ERROR cloudbaseinit.init   File "C:\Program Files\CloudBase\Python\lib\site-packages\cloudbaseinit\plugins\common\networkconfig.py", line 307, in execute
2020-06-09 13:45:54.101 1456 ERROR cloudbaseinit.init     return self._process_network_details_v2(network_details)
2020-06-09 13:45:54.101 1456 ERROR cloudbaseinit.init   File "C:\Program Files\CloudBase\Python\lib\site-packages\cloudbaseinit\plugins\common\networkconfig.py", line 300, in _process_network_details_v2
2020-06-09 13:45:54.101 1456 ERROR cloudbaseinit.init     osutils, network_details)
2020-06-09 13:45:54.101 1456 ERROR cloudbaseinit.init   File "C:\Program Files\CloudBase\Python\lib\site-packages\cloudbaseinit\plugins\common\networkconfig.py", line 286, in _process_networks
2020-06-09 13:45:54.101 1456 ERROR cloudbaseinit.init     net.link, ip_address, prefix_len, gateway, nameservers)
2020-06-09 13:45:54.101 1456 ERROR cloudbaseinit.init   File "C:\Program Files\CloudBase\Python\lib\site-packages\cloudbaseinit\osutils\windows.py", line 1005, in set_static_network_config
2020-06-09 13:45:54.101 1456 ERROR cloudbaseinit.init     name, address, prefix_len, gateway)
2020-06-09 13:45:54.101 1456 ERROR cloudbaseinit.init   File "C:\Program Files\CloudBase\Python\lib\site-packages\cloudbaseinit\osutils\windows.py", line 992, in _set_static_network_config
2020-06-09 13:45:54.101 1456 ERROR cloudbaseinit.init     conn.MSFT_NetIPAddress.create(
2020-06-09 13:45:54.101 1456 ERROR cloudbaseinit.init   File "C:\Program Files\CloudBase\Python\lib\site-packages\wmi.py", line 841, in __getattr__
2020-06-09 13:45:54.101 1456 ERROR cloudbaseinit.init     return _wmi_object.__getattr__(self, attribute)
2020-06-09 13:45:54.101 1456 ERROR cloudbaseinit.init   File "C:\Program Files\CloudBase\Python\lib\site-packages\wmi.py", line 605, in __getattr__
2020-06-09 13:45:54.101 1456 ERROR cloudbaseinit.init     handle_com_error()
2020-06-09 13:45:54.101 1456 ERROR cloudbaseinit.init   File "C:\Program Files\CloudBase\Python\lib\site-packages\wmi.py", line 258, in handle_com_error
2020-06-09 13:45:54.101 1456 ERROR cloudbaseinit.init     raise klass(com_error=err)
2020-06-09 13:45:54.101 1456 ERROR cloudbaseinit.init wmi.x_wmi: <x_wmi: Unexpected COM Error (-2147352567, 'Exception occurred.', (0, 'SWbemObjectEx', 'Invalid parameter ', None, 0, -2147217400), None)>
2020-06-09 13:45:54.101 1456 ERROR cloudbaseinit.init
```
Interfaces renamed, but addresses cannot be assigned.  Service WM is runned, after fer hours i try manual run service cloud-init, and receive same exceptions in log.

This log given from fresh install Windows 2012R2 (EN and RU editions), downloaded from VLSC Portal. 

Affected version: `1.1.2.dev4`

**Comment by ader1990** [comment]
Hello,

Have you used the beta or the stable Cloudbase-Init installer? This error usually appears when the pymi module is not properly loaded because of a missing VC runtime dll on the system. 

As a first step, please try the latest Cloudbase-Init installer from  https://www.cloudbase.it/downloads/CloudbaseInitSetup_x64.msi .

Thank you,
Adrian Vladu

**Comment by panaceya** [comment]
> Hello,
> 
> Have you used the beta or the stable Cloudbase-Init installer? This error usually appears when the pymi module is not properly loaded because of a missing VC runtime dll on the system.
> 
> As a first step, please try the latest Cloudbase-Init installer from https://www.cloudbase.it/downloads/CloudbaseInitSetup_x64.msi .
> 
> Thank you,
> Adrian Vladu

I`m use beta version of installer (1.1.2.dev4).

**Comment by ader1990** [comment]
I have tried with the latest version of the installer (1.1.2.dev5) on a Windows Server 2012 R2 Standard VM and I could not reproduce the error. Make sure that the Windows image has all the updates installed before Cloudbase-Init is installed.

**Comment by ader1990** [comment]
Hello @panaceya. 
did you try using the latest installer?

**Comment by panaceya** [comment]
Hello, 
I`m found problem with **WUA API**: some happen, and not get list of available updates after two first refresh + update (+ reboot if need), and not all updates installed on OS. 

This issue must closed, because bug in Windows WUA API. Sanks
