### ISSUE TITLE
No available service found

### ISSUE THREAD

**Issue by thel1zardking** [cloudbase/cloudbase-init#51]
Hello,

I am having issues in a particular environment using and image with cloudbase-init that works fine in another.  For some reason in this environment I get the following even thought he VM properly pulls and IP from nova network.  I suspect that possibly the VM doesn't have an IP by the time Cloudbase-Init executes but it's hard to be certain.  Any assistance regarding this great app would be greatly appreciated.

cloudbase-init.log
==================
2014-03-19 02:00:35.006 2172 ERROR cloudbaseinit.metadata.services.ec2service [-] 
2014-03-19 02:00:35.006 2172 TRACE cloudbaseinit.metadata.services.ec2service Traceback (most recent call last):
2014-03-19 02:00:35.006 2172 TRACE cloudbaseinit.metadata.services.ec2service   File "C:\Program Files (x86)\Cloudbase Solutions\Cloudbase-Init\Python27\lib\site-packages\cloudbaseinit\metadata\services\ec2service.py", line 49, in load
2014-03-19 02:00:35.006 2172 TRACE cloudbaseinit.metadata.services.ec2service     self.get_host_name()
2014-03-19 02:00:35.006 2172 TRACE cloudbaseinit.metadata.services.ec2service   File "C:\Program Files (x86)\Cloudbase Solutions\Cloudbase-Init\Python27\lib\site-packages\cloudbaseinit\metadata\services\ec2service.py", line 77, in get_host_name
2014-03-19 02:00:35.006 2172 TRACE cloudbaseinit.metadata.services.ec2service     self._metadata_version)
2014-03-19 02:00:35.006 2172 TRACE cloudbaseinit.metadata.services.ec2service   File "C:\Program Files (x86)\Cloudbase Solutions\Cloudbase-Init\Python27\lib\site-packages\cloudbaseinit\metadata\services\base.py", line 77, in _get_cache_data
2014-03-19 02:00:35.006 2172 TRACE cloudbaseinit.metadata.services.ec2service     data = self._exec_with_retry(lambda: self._get_data(path))
2014-03-19 02:00:35.006 2172 TRACE cloudbaseinit.metadata.services.ec2service   File "C:\Program Files (x86)\Cloudbase Solutions\Cloudbase-Init\Python27\lib\site-packages\cloudbaseinit\metadata\services\base.py", line 62, in _exec_with_retry
2014-03-19 02:00:35.006 2172 TRACE cloudbaseinit.metadata.services.ec2service     return action()
2014-03-19 02:00:35.006 2172 TRACE cloudbaseinit.metadata.services.ec2service   File "C:\Program Files (x86)\Cloudbase Solutions\Cloudbase-Init\Python27\lib\site-packages\cloudbaseinit\metadata\services\base.py", line 77, in <lambda>
2014-03-19 02:00:35.006 2172 TRACE cloudbaseinit.metadata.services.ec2service     data = self._exec_with_retry(lambda: self._get_data(path))
2014-03-19 02:00:35.006 2172 TRACE cloudbaseinit.metadata.services.ec2service   File "C:\Program Files (x86)\Cloudbase Solutions\Cloudbase-Init\Python27\lib\site-packages\cloudbaseinit\metadata\services\ec2service.py", line 72, in _get_data
2014-03-19 02:00:35.006 2172 TRACE cloudbaseinit.metadata.services.ec2service     response = self._get_response(req)
2014-03-19 02:00:35.006 2172 TRACE cloudbaseinit.metadata.services.ec2service   File "C:\Program Files (x86)\Cloudbase Solutions\Cloudbase-Init\Python27\lib\site-packages\cloudbaseinit\metadata\services\ec2service.py", line 62, in _get_response
2014-03-19 02:00:35.006 2172 TRACE cloudbaseinit.metadata.services.ec2service     raise base.NotExistingMetadataException()
2014-03-19 02:00:35.006 2172 TRACE cloudbaseinit.metadata.services.ec2service NotExistingMetadataException
2014-03-19 02:00:35.006 2172 TRACE cloudbaseinit.metadata.services.ec2service 
2014-03-19 02:00:35.115 2172 CRITICAL cloudbaseinit [-] Exception: No available service found
2014-03-19 02:00:35.115 2172 TRACE cloudbaseinit Traceback (most recent call last):
2014-03-19 02:00:35.115 2172 TRACE cloudbaseinit   File "C:\Program Files (x86)\Cloudbase Solutions\Cloudbase-Init\Python27\Scripts\cloudbase-init-script.py", line 9, in <module>
2014-03-19 02:00:35.115 2172 TRACE cloudbaseinit     load_entry_point('cloudbase-init==0.9.6.dev150.g621e7c1', 'console_scripts', 'cloudbase-init')()
2014-03-19 02:00:35.115 2172 TRACE cloudbaseinit   File "C:\Program Files (x86)\Cloudbase Solutions\Cloudbase-Init\Python27\lib\site-packages\cloudbaseinit\shell.py", line 31, in main
2014-03-19 02:00:35.115 2172 TRACE cloudbaseinit     init.InitManager().configure_host()
2014-03-19 02:00:35.115 2172 TRACE cloudbaseinit   File "C:\Program Files (x86)\Cloudbase Solutions\Cloudbase-Init\Python27\lib\site-packages\cloudbaseinit\init.py", line 102, in configure_host
2014-03-19 02:00:35.115 2172 TRACE cloudbaseinit     service = metadata_factory.get_metadata_service()
2014-03-19 02:00:35.115 2172 TRACE cloudbaseinit   File "C:\Program Files (x86)\Cloudbase Solutions\Cloudbase-Init\Python27\lib\site-packages\cloudbaseinit\metadata\factory.py", line 53, in get_metadata_service
2014-03-19 02:00:35.115 2172 TRACE cloudbaseinit     raise Exception("No available service found")
2014-03-19 02:00:35.115 2172 TRACE cloudbaseinit Exception: No available service found
2014-03-19 02:00:35.115 2172 TRACE cloudbaseinit

**Comment by ociuhandu** [comment]
Since the project is moved to StackForge, we are going to mark the issue as closed here.
