### ISSUE TITLE
Should catch SerialException so cloudbase-init will still run

### ISSUE THREAD

**Issue by blakerouse** [cloudbase/cloudbase-init#78]
On a Windows node deployed with MAAS the following happens if the COM port cannot be open for cloudbase-init. This stops cloudbase-init from continuing, making the node unusable. 

2014-09-08 20:33:11.408 1912 CRITICAL cloudbaseinit [-] SerialException: could not open port 'COM1': WindowsError(2, 'The system cannot find the file specified.')
2014-09-08 20:33:11.408 1912 TRACE cloudbaseinit Traceback (most recent call last):
2014-09-08 20:33:11.408 1912 TRACE cloudbaseinit   File "C:\Program Files (x86)\Cloudbase Solutions\Cloudbase-Init\Python27\Scripts\cloudbase-init-script.py", line 9, in <module>
2014-09-08 20:33:11.408 1912 TRACE cloudbaseinit     load_entry_point('cloudbase-init==0.9.6.dev212.gc996169', 'console_scripts', 'cloudbase-init')()
2014-09-08 20:33:11.408 1912 TRACE cloudbaseinit   File "C:\Program Files (x86)\Cloudbase Solutions\Cloudbase-Init\Python27\lib\site-packages\cloudbaseinit\shell.py", line 29, in main
2014-09-08 20:33:11.408 1912 TRACE cloudbaseinit     logging.setup('cloudbaseinit')
2014-09-08 20:33:11.408 1912 TRACE cloudbaseinit   File "C:\Program Files (x86)\Cloudbase Solutions\Cloudbase-Init\Python27\lib\site-packages\cloudbaseinit\utils\log.py", line 59, in setup
2014-09-08 20:33:11.408 1912 TRACE cloudbaseinit     serialportlog = SerialPortHandler()
2014-09-08 20:33:11.408 1912 TRACE cloudbaseinit   File "C:\Program Files (x86)\Cloudbase Solutions\Cloudbase-Init\Python27\lib\site-packages\cloudbaseinit\utils\log.py", line 42, in __init__
2014-09-08 20:33:11.408 1912 TRACE cloudbaseinit     bytesize=int(settings[3]))
2014-09-08 20:33:11.408 1912 TRACE cloudbaseinit   File "C:\Program Files (x86)\Cloudbase Solutions\Cloudbase-Init\Python27\lib\site-packages\serial\serialwin32.py", line 38, in __init__
2014-09-08 20:33:11.408 1912 TRACE cloudbaseinit     SerialBase.__init__(self, *args, **kwargs)
2014-09-08 20:33:11.408 1912 TRACE cloudbaseinit   File "C:\Program Files (x86)\Cloudbase Solutions\Cloudbase-Init\Python27\lib\site-packages\serial\serialutil.py", line 282, in __init__
2014-09-08 20:33:11.408 1912 TRACE cloudbaseinit     self.open()
2014-09-08 20:33:11.408 1912 TRACE cloudbaseinit   File "C:\Program Files (x86)\Cloudbase Solutions\Cloudbase-Init\Python27\lib\site-packages\serial\serialwin32.py", line 66, in open
2014-09-08 20:33:11.408 1912 TRACE cloudbaseinit     raise SerialException("could not open port %r: %r" % (self.portstr, ctypes.WinError()))
2014-09-08 20:33:11.408 1912 TRACE cloudbaseinit SerialException: could not open port 'COM1': WindowsError(2, 'The system cannot find the file specified.')
2014-09-08 20:33:11.408 1912 TRACE cloudbaseinit

**Comment by ociuhandu** [comment]
Since the project is moved to StackForge, we are going to mark the issue as closed here.
